name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          DATABASE_URL: sqlite:///./test.db
        run: pytest --cov=app --cov-report=xml

      - name: Debug files
        run: ls -la

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=all-in-one-backend
            -Dsonar.organization=jhosue-pstr
            -Dsonar.sources=app
            -Dsonar.tests=test
            -Dsonar.python.coverage.reportPaths=./coverage.xml
